# Directory: 0
# TextFile: 1
- ino: 1
  name: root
  file-type: 0
  size: 2
  uid: 1000
  gid: 1000
  perm: 0o755 
- ino: 2
  name: file1
  file-type: 1
  size: 24
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 3
  name: directory1
  file-type: 0
  size: 1
  uid: 1000
  gid: 1000
  perm: 0o755 
- ino: 4
  name: file2
  file-type: 1
  size: 0
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 2
  name: file1
  file-type: 1
  size: 31
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 5
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 10
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 15
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 20
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 25
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 30
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 35
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 4
  name: file2
  file-type: 1
  size: 40
  uid: 1000
  gid: 1000
  perm: 0o644
- ino: 2
  name: file1
  file-type: 1
  size: 36
  uid: 1000
  gid: 1000
  perm: 0o644
