# Directory: 0
# TextFile: 1
- ino: 1
  name: root
  file-type: 0
  size: 2

- ino: 2
  name: file1
  file-type: 1
  size: 20

- ino: 3
  name: directory1
  file-type: 0
  size: 1

- ino: 4
  name: file2
  file-type: 1
  size: 0
